language: go
go:
- 1.12.x
before_install:
- mkdir -p $GOPATH/bin $GOPATH/src
install:
- OS= ARCH= curl https://glide.sh/get | sh
- glide install
script:
- go build -o mtr bin/main.go
- go test ./... -coverprofile=coverage.txt
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- chmod +x mtr
- tar -zcf mtr-${TRAVIS_TAG}.tar.gz mtr
deploy:
  provider: releases
  api_key:
    secure: oq6pox/rJcOELGxfTyV+UrZ57M4fegNiDsjYVwDyPXl8DCtuKXnZjvQNNFzx+z0rf3pp3cMfnvQR+LCLRM2ta9gw+SYDHkwW1RBq/UKFwAR49BfJAS7HAaZ+ZyCd45bh7SR06kwt9HLpd3Bh0aKJWWrSmnLUiSuGNwoCy6nwPhe4jG7eW8CBEF/6BfQr5/kM180d5S+7I8tWT2HKpTS0JwGJyJ+aBl+BVpl6tNyNCtHBzkTO1RpCDyfaVs0z6OxIKPUs018vXbxW5u8DCgrhQMm/9ICLcm4+legrChuIc2rbLitDVOZkZptUzWhcwanJKUsOjg2UvjwiBsEkxKL7FRaYc8t8TPQEemOnTmsPk8v05V//uLXiUICGpwpwPnoJxqpRnlFL2BnYS72VtyvPVgDtzIOroxz6lIQR+pgz2WNCV3BXZFNHv6621YFgkqjD8CBIve1k7CpejhbZ4/vc7SKFwqnETlfXZCZ50Ma5yecf7givZUnSimYbxM/7ULAP5E/ie1L4QZ3a5e2/2DSrDEpXThXg3sKGyBzNnWEXNuuaqZmMgLskYBVLFc8gZa4Kj/YJ+kc7iwSseJ8lbbSRFtDlGJIdqJJctPK9VeZKjhQM6etBMlawx0OYAaOleT6GGSas/Dmq3R/8PT3tD1VtsylzDCOIw+o92VMzpNYxzMs=
  file: mtr-go.tar.gz
  on:
    repo: untoreh/mtr-go
    tags: true
