language: go

go:
- 1.7.x
before_install:
- apt install curl
- export GOPATH=$PWD PATH=$GOPATH/bin:$PATH
install:
- echo $PWD
- mkdir -p $GOPATH/bin $GOPATH/src
- curl https://glide.sh/get | sh
- glide install
script:
- echo 0

#before_deploy:
#-
#deploy:
#  provider: releases
#  api_key:
#    secure:
#  file:
#  -
#  skip_cleanup: true
#  on:
#tags: true