language: go

go:
- 1.7.x
before_install:
# glide problems
- export OS= ARCH=
- mkdir -p $GOPATH/bin $GOPATH/src
install:
- curl https://glide.sh/get | sh
- glide install
script:
- go build bin/main.go

#before_deploy:
#-
#deploy:
#  provider: releases
#  api_key:
#    secure:
#  file:
#  -
#  skip_cleanup: true
#  on:
#tags: true